### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/community-portal#18]
### What

- [ ] Auto-assign PR
- [ ] Auto-generate release notes
- [ ] Dart format + Linting tests
- [ ] Automation of Deployment

**Comment by M123-dev** [comment]
I can do the testing

For the deploy, what is still needed
